fail_fast: true
repos:
  - repo: local
    hooks:
      - id: pl
        name: Pylint
        entry: task pylint
        language: system
        always_run: true
        pass_filenames: false
      - id: cs
        name: Pycodestyle
        entry: task pycodestyle
        language: system
        always_run: true
        pass_filenames: false
