name: Pylint & Pycodestyle

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  pylint:
    name: Run Pylint and Pycodestyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Pylint check
        run: pylint --max-line-length=120 --recursive=y .

      - name: Pycodestyle check
        run: pycodestyle --max-line-length=120 --show-source .
