name: Release

on:
  release:
    types:
      - published

env:
  DOCKER_IMAGE: t0shy/pexels-scraper

jobs:
  release:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build & Push | Development image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: dev
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ env.DOCKER_IMAGE }}:dev
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build & Push | Production image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: prod
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
